name: Ejemplo Github Actions Java

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout de proyecto
      uses: actions/checkout@v4
